### ISSUE TITLE
When will the next release?

### ISSUE THREAD

**Issue by jershell** [VerachadW/kraph#29]
I want to use the feature(https://github.com/VerachadW/kraph/pull/23), but it not found in 0.6.0. It is my mistake or it is not included in version 0.6.0?

**Comment by olereidar** [comment]
Hello; I am bumping this thread 😄 
Will there be a new release version soon? 
I found a commit in the develop branch that would be awesome  https://github.com/VerachadW/kraph/commit/2b3984173f893c31b565e5c8141e2d25a1b23d0c

**Comment by huehnerlady** [comment]
Hi, bumping this again. how does it look?

I would need the variable support in order to use it, otherwise it is useless for me unfortunately

**Comment by VerachadW** [comment]
Hi, I just published the `0.6.1` with variable support. Please let me know is it work for you. I will close this issue for now.
