### ISSUE TITLE
Support for enum types as args?

### ISSUE THREAD

**Issue by keck** [VerachadW/kraph#33]
With a query like:

`query {
  getUser (input: { userId: "123", userType: admin }) {
    id
    name
    whatever
  }
}`

Where 'type' in my schema is an enum:

`enum UserType {
  normal
  admin
}`

If I give it a String, it quotes the argument, which fails validation, but if I create a kotlin enum class, convertToDataEntry does not handle it.

Am I missing something or is this not supported right now?

**Comment by VerachadW** [comment]
Hi @keck . Sorry for they delay. Enum support are now in `0.6.1`. I will close this issue
