### ISSUE TITLE
Support for variables

### ISSUE THREAD

**Issue by AlexeySoshin** [VerachadW/kraph#34]
Is there support for query variables?

I've found that there's additional DSL for variables in this fork:
https://github.com/makarenkoanton/kraph

But I don't see it in the main project.

**Comment by AlexeySoshin** [comment]
https://github.com/VerachadW/kraph/pull/23/files

**Comment by AlexeySoshin** [comment]
@VerachadW Maybe pushing `0.6.1` will resolve this, since `master` does contain this feature.

**Comment by VerachadW** [comment]
Yes. I have problem to deploy a new version. I will merge #35 and try again tonight.

**Comment by VerachadW** [comment]
The problem solved and I publish `0.6.1` release. I will close this issue. Thanks for your contribution
